### ISSUE TITLE
Port to use with Aurelia

### ISSUE THREAD

**Issue by PWKad** [timstuyckens/chromeextensions-knockoutjs#25]
Hello @timstuyckens -

I would like to port this extension to work with Aurelia but before I did I wanted to see if you would be interested in contributing as well or would prefer for me not to.

Thanks in advance.

**Comment by timstuyckens** [comment]
Hi,

From what I understand of http://aurelia.io/ , it doens't seem that knockout is used.
What would be needed to use the extension with aurelia? Can it be done by adding ES6 module support to https://github.com/timstuyckens/chromeextensions-knockoutjs/blob/master/pages/js/devtools.js#L9 ?

I am interested, but I don't want to break the current behaviour.


PS For the ecosystem, I think that 1 extension is great, easier to discover in the chrome extension store.

**Comment by PWKad** [comment]
Yes you are correct, by default it uses it's own binding system but you can of course use whichever.  My thought was to port this to a clean extension that doesn't affect the current Knockout Context Debugger.

**Comment by timstuyckens** [comment]
Is there a sample with knockoutjs somewhere?
I would like to see why it doesn't work currently.

Do you want to provide aurelia specific features? Because I don't see the benefit of a seperate extension. People working on multiple projects would have to install multiple extensions etc.

**Comment by PWKad** [comment]
Sorry think there must be a mis-communication :)  When using knockout it is fine but I was hoping to use the base logic and such in this app to perform the same thing in a separate app for the aurelia binding system.

I will close this out and just start fresh though.

**Comment by timstuyckens** [comment]
I'm sorry, I misunderstood :)
A seperate extension would be the way to go.Currently there is a lot of code specific for knockout ($roots stuff etc). As I am currently doing angularjs and won't be doing any aurelia in the near future, I am not really interested in contributing.
Thanks for asking though!

I used the following example as starting point (https://developer.chrome.com/extensions/samples#search:): 

![image](https://cloud.githubusercontent.com/assets/1768681/6243647/5b3d1028-b746-11e4-9404-2dde7a9c66d2.png)
