### ISSUE TITLE
Not working on Chrome 46

### ISSUE THREAD

**Issue by stephenwil** [timstuyckens/chromeextensions-knockoutjs#27]
Hi,
  No tracing is observed when used in Chrome 46; The knockout context does show under the 'elements' panel, but obviously this doesn't show any data change.

Thanks

Stephen

**Comment by timstuyckens** [comment]
Hi, 

I tried to find a specific chrome 46 issue but couldn't reproduce.

Knockout context. Their is a long standing (not fixable) issue with not being realtime #4 
![image](https://cloud.githubusercontent.com/assets/1768681/10715042/70b59bfc-7b07-11e5-9e0d-7c0dd50313c7.png)


The tracing panel
![image](https://cloud.githubusercontent.com/assets/1768681/10715038/25a2b8d4-7b07-11e5-830d-4bf8a88f4e24.png)
