### ISSUE TITLE
get All context data as JSON format

### ISSUE THREAD

**Issue by tayfunyasar** [timstuyckens/chromeextensions-knockoutjs#30]
How to get All context data as JSON format?

I'm searching a value in somewhere in context. Need to find it easly.

**Comment by timstuyckens** [comment]
Hi, 

You don't need the extension for that, you can just select an element and past the following

```javascript
ko.toJSON(ko.contextFor($0).$root, null, 0)


![ko tojson](https://cloud.githubusercontent.com/assets/1768681/12004372/65b81748-ab54-11e5-9836-c6a640ce2fa7.PNG)

**Comment by tayfunyasar** [comment]
Thanks! I didnt know.
