### ISSUE TITLE
ko not found in webpack project

### ISSUE THREAD

**Issue by cosmoKenney** [timstuyckens/chromeextensions-knockoutjs#34]
I'm bundling knockout with webpack. Like issue #6 I get the error: _knockout.js is not used in the page (ko is undefined). Maybe you are using iFrames, if so, browse to the url of the frame and try again._
I've tried (this is typescript) in my entry point:

`
		(<any>window).ko = ko;
`

**Comment by cosmoKenney** [comment]
Would the webpack ProvidePlugin help with this?

**Comment by crmtestresco** [comment]
You can use [expose loader](https://webpack.js.org/loaders/expose-loader/) to make knockout global variable again.
Example configuration: 
```
rules: [
  {
    test: require.resolve('knockout'),
    use: [
      {
        loader: 'expose-loader',
        options: 'ko',
      },
    ],
  },
],
```

You can also use this configuration only for development mode.

**Comment by cosmoKenney** [comment]
Thanks. I've moved to Angular so this is no longer an issue for me.
