### ISSUE TITLE
Privacy statement 

### ISSUE THREAD

**Issue by luismox** [timstuyckens/chromeextensions-knockoutjs#36]
Do you have any privacy statement about this chrome extension?

I would like to add your extension in our corporate white list chrome extensions, but I can't without this statement.

thank you

**Comment by timstuyckens** [comment]
Generated something with https://getterms.io/
https://github.com/timstuyckens/chromeextensions-knockoutjs/blob/master/privacy.md

Is this enough to get the extension white listed ?

Kind regards,

Tim.

**Comment by luismox** [comment]
It's perfect, Thanks
