### ISSUE TITLE
Extension not working in the latest version of Google Chrome

### ISSUE THREAD

**Issue by MaiconSlavieiro** [timstuyckens/chromeextensions-knockoutjs#38]
Stopped working after updating the Chrome version to 92.0.4515.107

**Comment by Usuario001** [comment]
Same problem:
  Chrome Versión 92.0.4515.107 (Build oficial) (64 bits)

**Comment by ozknozsrt** [comment]
Yes, same problem and same version.
When I look plugin logs, I've see these problems:
1. https://prnt.sc/1hic6ju
2. https://prnt.sc/1hidv3h

And here I see stuck of the error on background.js:
https://prnt.sc/1hiedvi

maybe the sendMessage function is not working.

**Comment by ozknozsrt** [comment]
By the way, when I debug the plugin, it throws an error like this:
https://prnt.sc/1hkh5il

When I look at the incoming **tab.id**, it shows as **-1**. Maybe it's because of that
https://prnt.sc/1hkibrp

**Comment by maxime-paquatte** [comment]
> By the way, when I debug the plugin, it throws an error like this:
> https://prnt.sc/1hkh5il
> 
> When I look at the incoming **tab.id**, it shows as **-1**. Maybe it's because of that
> https://prnt.sc/1hkibrp


This is not the problème. 
In [devtool.js](https://github.com/timstuyckens/chromeextensions-knockoutjs/blob/master/pages/js/devtools.js) line 193

He call `sidebar.setExpression(` and the function does not work anymore : 

https://bugs.chromium.org/p/chromium/issues/detail?id=1233027&q=object_ui&can=2

![devtool](https://user-images.githubusercontent.com/1065839/127483006-ff054727-0067-494f-9793-bd4257683461.PNG)

**Comment by rwhepburn** [comment]
Same issue here: 92.0.4515.107 (Official Build) (64-bit)

**Comment by maxime-paquatte** [comment]
> Anyone found a workaround?

I inspect the element then I use this in console : 

`ko.contextFor($0)`

**Comment by ozknozsrt** [comment]
I use this temporarily as snippet

![image](https://user-images.githubusercontent.com/11375802/128081792-c9e0d520-93de-4a4c-b61c-47173980c642.png)

After defining it as a snippet, I click "ctrl + p" in the console tab and "!" I add the mark and call the snippet I defined.

**Comment by barsh** [comment]
Here's another workaround.  Add this expression to devtools:

```
if (window.last$0 !== $0) { window.last$0 = $0; console.log('\n\n-------------- Knockout $data ------------\n', 'element:', $0, '\n', ko.toJS(ko.dataFor($0)), '\n\n\n')}
```

![expressions are cool](https://user-images.githubusercontent.com/2644202/128095097-e9fbcbe2-e903-4672-a995-546c693fafee.gif)

**Comment by Usuario001** [comment]
> Here's another workaround. Add this expression to devtools:
> 
> ```
> if (window.last$0 !== $0) { window.last$0 = $0; console.log('\n\n-------------- Knockout $data ------------\n', 'element:', $0, '\n', ko.toJS(ko.dataFor($0)), '\n\n\n')}
> ```
> 
> ![expressions are cool](https://user-images.githubusercontent.com/2644202/128095097-e9fbcbe2-e903-4672-a995-546c693fafee.gif)

Additional to this, If you are a Magento 2 framework js developer or something add this: 
> ``` 
>  var ko = require('ko');
> ```
 at the beginning of the line.

**Comment by rwhepburn** [comment]
> > Here's another workaround. Add this expression to devtools:
> > ```
> > if (window.last$0 !== $0) { window.last$0 = $0; console.log('\n\n-------------- Knockout $data ------------\n', 'element:', $0, '\n', ko.toJS(ko.dataFor($0)), '\n\n\n')}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![expressions are cool](https://user-images.githubusercontent.com/2644202/128095097-e9fbcbe2-e903-4672-a995-546c693fafee.gif)
> 
> Additional to this, If you are a Magento 2 framework js developer or something add this:
> 
> > ```
> >  var ko = require('ko');
> > ```
> 
> at the beginning of the line.

Thanks for the workarounds! Here's a small improvement to the dev tools expression to also show binding context for the current element:

`if (window.last$0 !== $0) { window.last$0 = $0; console.log('\n\n-------------- Knockout $data ------------\n', 'element:', $0, '\n data:', ko.toJS(ko.dataFor($0)),'\n context:', ko.contextFor($0));}
`

**Comment by dre99gsx** [comment]
"fixed in canary  94.0.4605.0" - an issue in GUI was found.
[https://bugs.chromium.org/p/chromium/issues/detail?id=1233027](url)

**Comment by timlaughlin** [comment]
@ajc-uconn It is a chrome problem and not the extension. It is fixed in the "nightly" chrome version https://www.google.com/chrome/canary/

**Comment by ozknozsrt** [comment]
I'm updated the Chrome to 93.0.4577.63 version and working anymore this to me.
