### ISSUE TITLE
Update to WebExtensions API to support Firefox browser

### ISSUE THREAD

**Issue by gerbendekker** [timstuyckens/chromeextensions-knockoutjs#39]
Tested and updated this plugin to WebExtensions API and that made it compatible with Firefox.
Also working with Chrome version 90, tested that version due to resent issue with Chrome 92 #38 .

Here some image of the results in FF:
![image](https://user-images.githubusercontent.com/11212123/128694930-f42d97e3-5457-49bc-9fcc-0e2fa9d81a9c.png)
![image](https://user-images.githubusercontent.com/11212123/128694944-458e9534-6f8d-46e0-a2db-6812ed2e1ec9.png)
![image](https://user-images.githubusercontent.com/11212123/128694949-404159f2-a21c-40ad-b340-656931602992.png)
![image](https://user-images.githubusercontent.com/11212123/128694976-9a9207f0-3be1-4f4c-927a-bb9b60c6d67e.png)
![image](https://user-images.githubusercontent.com/11212123/128694992-95936cda-29f4-45e9-9f71-37e110516591.png)

**Comment by timstuyckens** [comment]
Hi,

Thanks for the pull request!
I tried uploading it in the firefox dev portal but it doesn't allow jQuery 2.x anymore

![image](https://user-images.githubusercontent.com/1768681/128703309-b4eaaa45-3a6b-4b82-aff2-15481e0192cd.png)

**Comment by timstuyckens** [comment]
![image](https://user-images.githubusercontent.com/1768681/128828442-78e0011e-faf3-42ce-8bb6-34eca18d8344.png)

**Comment by timstuyckens** [comment]
Approved
https://addons.mozilla.org/nl/firefox/addon/knockoutjs-context/
