### ISSUE TITLE
Removed from Chrome Web Store

### ISSUE THREAD

**Issue by duffdean** [timstuyckens/chromeextensions-knockoutjs#46]
Hi, 

I noticed this has been removed from the extension web store in Chrome. Is there any way this can be resubmitted?

Or is there any details on why this was violating their policy so we could make code changes so that it can be resubmitted? As it is such a useful tool, it makes debugging so much easier and quicker, it would be a shame to see this extension go.

Cheers!

**Comment by KarthikMadathil** [comment]
Yeah. im also looking for debug UiComponent

**Comment by danieluniform** [comment]
Yes, this is going to be a real pain in our development pipeline if the knockoutjs debugger is completely removed, as it's almost vital for us to fix problems in our builds as our whole app is virtually centered around Knockoutjs.

**Comment by timstuyckens** [comment]
Hi All,

Details about the removal (from a email from the webstore):


`We want to let you know that your item is at risk of being removed from the Chrome Web Store. You will find more information below.


Item name: Knockoutjs context debugger

Item ID: oddcpmchholgcjgjdnfjmildmlielhof

Violation(s):

Use of rights:

Reference ID Violation: Purple Potassium
Violation: The following permissions are not required to be requested for the methods/properties implemented by the item:
tabs
Correction: Remove the above permissions. The properties used by the items will continue to function without these rights being requested.
Relevant section in the program policy:
Request access to the most specific permissions needed to implement your product's features or services. You may not "prepare your product for the future" by applying for a right that can be used for services or features that have not yet been implemented. (more information)


Important information about new submissions:

Make the necessary changes within fourteen days to avoid deletion.`

**Comment by duffdean** [comment]
Don't know if this is too late, but you can submit this is an incorrect removal via https://support.google.com/chrome_webstore/contact/one_stop_support

After review Google should reinstate the extension. Have you tried this at all?

**Comment by rbailey90** [comment]
As a workaround for now, you can download the repo, unzip, then in Edge/Chrome, Manage Extensions, turn on Developer mode, click Load Unpacked and select the chromeextensions-knockoutjs-master folder.

The only downside is that the browser starts to nag you about the dangers of using extensions in developer mode and asking if you want to turn it off.

**Comment by duffdean** [comment]
@[rbailey90](https://github.com/rbailey90) Thanks for that advice! I think I will use this as a workaround for the time being.

@[timstuyckens](https://github.com/timstuyckens) Is there any way that the extension can be resubmitted with the suggest fix to see if this was the root cause?

**Comment by danieluniform** [comment]
From what I can tell from their response, and my *assumptions* just glancing at the code and looking in manifest.json, is that this needs to change from this:
`  "permissions": [
    "tabs"
  ],`

to this:
`  "permissions": [],`

Why this permission is *not* needed ? Shrug.

**Comment by duffdean** [comment]
Yeah was wondering if this could just be resubmitted to the store with the manifest updated to `"permissions": [],` ?
I could make the amendments and submit to the web store on my own account, but I don't own the extensions. But i would be happy to resubmit given permission.

**Comment by roman204** [comment]
> @[rbailey90](https://github.com/rbailey90) Thanks for that advice! I think I will use this as a workaround for the time being.
> 
> @[timstuyckens](https://github.com/timstuyckens) Is there any way that the extension can be resubmitted with the suggest fix to see if this was the root cause?

Did that and for now its working again. THX

**Comment by MarcelJurtz** [comment]
@danieluniform apparently the "tabs"-permission is still required, background.js uses this to handle page refreshes. This however makes me unsure on what the actual problem is. 

If this repo is no longer actively maintained, I'd also be happy to fix the issue in a fork, but this doesn't seem to address the problem correctly.

**Comment by gerbendekker** [comment]
![image](https://user-images.githubusercontent.com/11212123/183880507-814b3603-6eb0-48cc-88de-8f5942b3b19b.png)
How I read this and looking at what is used in the code `chrome.tabs.query({ active: true }` we don't require this permission.
Ill make a pull request for that

PS the [FF extension](https://addons.mozilla.org/nl/firefox/addon/knockoutjs-context/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) is still available

**Comment by timstuyckens** [comment]
@gerbendekker thanks for the PR
Long overdue I checked the developer dashboard and did some of the new requirements (filling in privacy description form, ... )
I cannot publish a new version untill they review this and "unblock" the extension

![image](https://user-images.githubusercontent.com/1768681/183895980-79f2f490-e9f6-4826-a30d-7bd43d1a468e.png)

**Comment by gerbendekker** [comment]
@timstuyckens dankjewel!
![image](https://user-images.githubusercontent.com/11212123/188286242-e2aa9036-246b-470a-abfe-2a936840715f.png)
